### ISSUE TITLE
CI failing because publishing same version of package

### ISSUE THREAD

**Issue by amilajack** [phanect/eslint-plugin-editorconfig#3] opened 2018-10-07 16:54 UTC
I will look into this more and try to PR. not very familiar with circle ci so might take some time

**Comment by phanect** [comment] 2018-10-07 17:01
This is expected behavior and no action required. The failed status will be fixed when another PR is merged next time.

This issue happened when I rebased master.
When new commits added to `master`, CircleCI run `npm publish` automatically, but it failed because the version number is not updated.

Generally, I don't push master directly, but this time I wanted to rebase a lot of `!fixup` commits which I forgot to rebase before.

**Closed by phanect** 2018-10-07 17:01 UTC

**Comment by phanect** [comment] 2018-10-07 20:16
I found this issue also happens when I merge PR without updating the `version` in package.json.
It should be fixed in 2b1c6ed.
